### ISSUE TITLE
Implements states for theme customization

### ISSUE THREAD

**Issue by AymericBriereJAC** [Carlos-LX/5A6-group-project#15]
**Requirement Description**
Implement a setting page where we can update background color, 

```[tasklist]
### Tasks
- [ ] Add a setting/ customization page
- [ ] Add options to the page such as fonts, fonts color, background color
- [ ] Implement states to be usable app- wide
```

**Effort estimation (LOE)**
8/10

**Comment by AymericBriereJAC** [comment]
states were implemented for a dark and light theme. Font state also implemented, but not integrated to the rest of the code
